controller_list:
  - name: fake_r_arm_controller
    joints:
      - R_Shoulder1_Joint
      - R_Shoulder2_Joint
      - R_Shoulder3_Joint
      - R_Armlink_Joint
      - R_Elbow_Joint
      - R_Forearm_Joint
      - R_Wrist1_Joint
      - R_Wrist2_Joint
  - name: fake_l_arm_controller
    joints:
      - L_Shoulder1_Joint
      - L_Shoulder2_Joint
      - L_Shoulder3_Joint
      - L_Armlink_Joint
      - L_Elbow_Joint
      - L_Forearm_Joint
      - L_Wrist1_Joint
      - L_Wrist2_Joint
  - name: fake_r_hand_controller
    joints:
      - R_Wrist2_Joint
  - name: fake_l_hand_controller
    joints:
      - L_Wrist2_Joint